import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Background from "../public/assets/about-001_1632925325.jpg";
import styles from "../styles/About.module.css";

import data from "../components/RacingCV";
import bio from "../components/AlexBio";

const About = () => {
  return (
    <>
      <Head>
        <title>Alex T Jones | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className={styles.about_hero_bg}>
          <Image
            src={Background}
            alt="Alex driving his mazda in front of a gorgeous orange sunset horizon!"
          />
          <h1>ABOUT ALEX</h1>
        </div>
        <div className={styles.about_cv_wrap}>
          <h2>Racing CV</h2>
          {data.map((item) => (
            <section className={styles.about_cv_item}>
              <section className={styles.about_cv_text}>
                <h4>{item.Year}</h4>
                <p>{item.Text}</p>
              </section>
              <Image src={item.Image} />
            </section>
          ))}
        </div>
        <div className={styles.about_bio_wrap}>
          <h2>ALEX JONES</h2>
          {bio.map((item) => (
            <section className={styles.about_bio_item}>
              <h5 className={styles.about_bio_question}>{item.Question}</h5>
              <h5 className={styles.about_bio_answer}>{item.Answer}</h5>
            </section>
          ))}
        </div>
      </main>
    </>
  );
};

export default About;
