import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import React, { useRef } from "react";
import emailjs from "@emailjs/browser";

import Background from "../public/assets/image 13.jpg";

import styles from "../styles/Contact.module.css";

const About = () => {
  const form = useRef();

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs
      .sendForm({process.env.EMAILJS_SERVICE_ID},
        {process.env.EMAILJS_TEMPLATE_KEY},
        form.current,
        {process.env.EMAILJS_PUBLIC_KEY}
      )
      .then(
        (result) => {
          console.log(result.text);
        },
        (error) => {
          console.log(error.text);
        }
      );
  };
  return (
    <>
      <Head>
        <title>Alex T Jones | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className={styles.contact_hero_bg}>
          <Image
            src={Background}
            alt="Alex racing away from camera in front of a beautiful horizon!"
          />
          <h1>CONTACT</h1>
        </div>
        <form
          className={styles.contact_form_wrap}
          ref={form}
          onSubmit={sendEmail}
        >
          <input type="text" placeholder="Name" name="name" required />
          <input type="email" placeholder="Email" name="email" required />
          <textarea placeholder="Message" name="message" required />
          <input
            type="submit"
            value="Send"
            className={styles.contact_form_btn}
          />
        </form>
      </main>
    </>
  );
};

export default About;
