import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import Logo from "../public/assets/AJ_Hero_Logo.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alex T Jones | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <section className={styles.home_hero_bg}>
          <video
            playsInLine
            autoPlay
            muted
            loop
            poster="/assets/Video.Still002.png"
            className={styles.home_hero_vid}
          >
            <source
              src="/assets/Alex T Jones Racing_Edit.mp4"
              type="video/mp4"
            />
          </video>
          <Image src={Logo} alt="AJ Logo" />
        </section>
      </main>
    </>
  );
}
