import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Background from "../public/assets/Optimized-JonElseyBRSCC2022Brands_MX5SC-106 1.png";
import BRSCC from "../public/assets/image 15.png";
import Calendar from "../public/assets/image 12.png";
import TCRUK from "../public/assets/image 11.png";
import styles from "../styles/Mazda.module.css";

const About = () => {
  return (
    <>
      <Head>
        <title>Alex T Jones | Mazda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className={styles.mazda_hero_bg}>
          <Image
            src={Background}
            alt="Alex racing multiple cars in his mazda!"
          />
          <h1>MAZDA MX5 SUPERCUP</h1>
        </div>
        <section className={styles.mazda_content_wrap}>
          <Image src={BRSCC} alt="BRSCC Logo" />
          <ul>
            <li>Live video coverage on Facebook and Youtube</li>
            <li>It has a Mazda 2000cc engine</li>
            <li>GAZ race shocks are used</li>
            <li>It has a standard 6 speed gearbox</li>
            <li>Normal brakes as used in the road car</li>
            <li>Runs on the Avon ZZR controlled tyre</li>
            <li>The minimum weight of the car including driver is 1110kg</li>
            <li>Also has a roll cage</li>
            <li>
              On the weekend, it has qualifying and 3 races which are 20 mins
              each
            </li>
          </ul>
          <section className={styles.mazda_content_images}>
            <Image src={Calendar} />
            <Image src={TCRUK} />
          </section>
        </section>
      </main>
    </>
  );
};

export default About;
